fields:

  nom:
    extends: nom

  age:
    extends: age

  sexe:
    extends: sexe

  phone:
    label: Phone
    type: tel
    width: 1/2

  languematernelle:
    extends: languematernelle

  profession:
    extends: profession

  religionenfance:
    extends: religionenfance

  religionpresente:
    extends: religionpresente

  poslieudenaissance:
    extends: poslieudenaissance

  poslieudevie:
    extends: poslieudevie
